#
# jekyll (or plug-in defined) attributes -------------------------------------
#
name: wfjm's retro computing corner
url: https://wfjm.github.io
email: w.f.j.mueller@gsi.de
markdown: kramdown
#
defaults:
#   default for pages/posts: layout and permalink ---------
  -
    scope:
      path: ""
    values:
      layout: plain
  - 
    scope:
      path: ""
      type: pages
    values:
      layout: pages
  - 
    scope:
      path: ""
      type: posts
    values:
      layout: posts
      permalink: /blogs/:categories/:year-:month-:day-:title.html
  - 
    scope:
      path: "debug"
    values:
      layout: plain
  - 
    scope:
      path: "tests"
    values:
      layout: plain
#
#   default category for posts -----------------------------
  - 
    scope:
      path: "_posts/211bsd"
    values:
      category: 211bsd
      sdef_blog_proj: 211bsd
  - 
    scope:
      path: "_posts/ouxr"
    values:
      category: ouxr
      sdef_blog_proj: ouxr
  - 
    scope:
      path: "_posts/w11"
    values:
      category: w11
      sdef_blog_proj: w11

#
# site-specific attributes (all in .my subspace) -----------------------------
#
my:
  emptylist: []
#
  url_fa: "/tools/fa/fa-4.7.0/css/font-awesome.min.css"
  url_jq: "/tools/jq/jq-3.1.1/jquery-3.1.1.min.js"
#
  w3c_chtml: "https://validator.w3.org/check"
  w3c_clink: "https://validator.w3.org/checklink"
#
  w11:
    tree: https://github.com/wfjm/w11/tree/master
    blob: https://github.com/wfjm/w11/blob/master
    raw:  https://raw.githubusercontent.com/wfjm/w11/master
    manp: http://www.retro11.de/manp/w11/man
#
  ouxr:
    url_base:   http://www.retro11.de/ouxr
    url_211bsd: http://www.retro11.de/ouxr/211bsd
    url_29bsd:  http://www.retro11.de/ouxr/29bsd
    url_u6ed:   http://www.retro11.de/ouxr/u6ed
    url_u7ed:   http://www.retro11.de/ouxr/u6ed
