name: wfjm's retro computing corner
url: https://wfjm.github.io
email: w.f.j.mueller@gsi.de
markdown: kramdown
w11_tree: https://github.com/wfjm/w11/tree/master
w11_blob: https://github.com/wfjm/w11/blob/master
