#
# jekyll (or plug-in defined) attributes -------------------------------------
#
name: wfjm's retro computing corner
url: https://wfjm.github.io
email: w.f.j.mueller@gsi.de
markdown: kramdown
#
defaults:
#   default for pages/posts: layout and permalink ---------
  -
    scope:
      path: ""
    values:
      layout: plain
  - 
    scope:
      path: ""
      type: pages
    values:
      layout: pages
  - 
    scope:
      path: ""
      type: posts
    values:
      layout: posts
      permalink: /blogs/:categories/:year-:month-:day-:title.html
  - 
    scope:
      path: "debug"
    values:
      layout: plain
  - 
    scope:
      path: "tests"
    values:
      layout: plain
#
#   default category for posts -----------------------------
  - 
    scope:
      path: "_posts/211bsd"
    values:
      category: 211bsd
      sdef_blog_proj: 211bsd
  - 
    scope:
      path: "_posts/mvs"
    values:
      category: mvs
      sdef_blog_proj: mvs
  - 
    scope:
      path: "_posts/ouxr"
    values:
      category: ouxr
      sdef_blog_proj: ouxr
  - 
    scope:
      path: "_posts/w11"
    values:
      category: w11
      sdef_blog_proj: w11
#
# site-specific attributes (all in .my subspace) -----------------------------
#
my:
  emptylist: []
#
  wfjm-ccby: '(wfjm <a href="https://creativecommons.org/licenses/by/4.0/">cc-by-4.0</a>)'
#
  url_fa: "/tools/fa/fa-4.7.0/css/font-awesome.min.css"
  url_jq: "/tools/jq/jq-3.1.1/jquery-3.1.1.min.js"
#
  w3c_chtml: "https://validator.w3.org/check"
  w3c_clink: "https://validator.w3.org/checklink"
#
  gh_wfjm: https://github.com/wfjm
#
  bitsaver:
    dec:   http://www.bitsavers.org/pdf/dec
    pdp11: http://www.bitsavers.org/pdf/dec/pdp11
    uq:    http://www.bitsavers.org/www.computer.museum.uq.edu.au
#
  w11:
    top:  https://github.com/wfjm/w11
    tree: https://github.com/wfjm/w11/tree/master
    blob: https://github.com/wfjm/w11/blob/master
    comm: https://github.com/wfjm/w11/commit
    tag:  https://github.com/wfjm/w11/releases/tag
    raw:  https://raw.githubusercontent.com/wfjm/w11/master
    manp: https://www.retro11.de/manp/w11/man
#
  ouxr:
    url_base:   https://www.retro11.de/ouxr
    url_211bsd: https://www.retro11.de/ouxr/211bsd
    url_29bsd:  https://www.retro11.de/ouxr/29bsd
    url_u6ed:   https://www.retro11.de/ouxr/u6ed
    url_u7ed:   https://www.retro11.de/ouxr/u6ed
#
  mvs_lt:
    top:  https://github.com/wfjm/mvs38j-langtest
    tree: https://github.com/wfjm/mvs38j-langtest/tree/master
    blob: https://github.com/wfjm/mvs38j-langtest/blob/master
    comm: https://github.com/wfjm/mvs38j-langtest/commit
#
  mvs_sp:
    top:  https://github.com/wfjm/s370-perf
    tree: https://github.com/wfjm/s370-perf/tree/master
    blob: https://github.com/wfjm/s370-perf/blob/master
    comm: https://github.com/wfjm/s370-perf/commit
#
  mvs_ht:
    top:  https://github.com/wfjm/herc-tools
    tree: https://github.com/wfjm/herc-tools/tree/master
    blob: https://github.com/wfjm/herc-tools/blob/master
    comm: https://github.com/wfjm/herc-tools/commit
