# jekyll (or plug-in defined) attributes
#
name: wfjm's retro computing corner
url: https://wfjm.github.io
email: w.f.j.mueller@gsi.de
markdown: kramdown
#
# site-specific attributes (all in .my subspace)
#
my:
  emptylist: []
  emptyhash: {}
#
  url_fa: "/tools/fa/fa-4.7.0/css/font-awesome.min.css"
  url_jq: "/tools/jq/jq-3.1.1/jquery-3.1.1.min.js"
#
  w11:
    tree: https://github.com/wfjm/w11/tree/master
    blob: https://github.com/wfjm/w11/blob/master
